"""Provider-neutral model protocol and transport adapters."""

from app.vnext.llm.errors import ModelContextWindowError, ModelToolCallBatchRejected
from app.vnext.llm.openai_compatible import (
    OpenAICompatibleAdapter,
    OpenAICompatibleModelClient,
    ProviderHTTPError,
    ProviderProtocolError,
)
from app.vnext.llm.protocol import (
    AssistantMessage,
    FinalMessage,
    Message,
    ModelClient,
    ModelRequest,
    ModelResponse,
    ModelTextDelta,
    ModelTool,
    RawToolCall,
    RejectedToolCallBatch,
    StreamingModelClient,
    SystemMessage,
    ToolArgumentFailure,
    ToolCall,
    ToolError,
    ToolErrorCode,
    ToolResultMessage,
    UserMessage,
)

__all__ = [
    "AssistantMessage",
    "FinalMessage",
    "Message",
    "ModelContextWindowError",
    "ModelToolCallBatchRejected",
    "ModelClient",
    "ModelRequest",
    "ModelResponse",
    "ModelTextDelta",
    "ModelTool",
    "RawToolCall",
    "RejectedToolCallBatch",
    "OpenAICompatibleAdapter",
    "OpenAICompatibleModelClient",
    "ProviderHTTPError",
    "ProviderProtocolError",
    "SystemMessage",
    "StreamingModelClient",
    "ToolError",
    "ToolErrorCode",
    "ToolArgumentFailure",
    "ToolCall",
    "ToolResultMessage",
    "UserMessage",
]
